---
# code: language=ansible

docker_path: "/home/{{ username }}/docker"

timezone: "Europe/Minsk"

images:
  traefik: "traefik:v3.6.1"
  qbittorrent: "lscr.io/linuxserver/qbittorrent:5.1.4"
  vaultwarden: "vaultwarden/server:1.34.3"
  plex: "lscr.io/linuxserver/plex:1.42.2"
  nextcloud: "lscr.io/linuxserver/nextcloud:32.0.3"
