---
# code: language=ansible

docker_path: "/home/{{ username }}/docker"

timezone: "Europe/Minsk"

images:
  traefik: "traefik:v3.6.5"
  qbittorrent: "lscr.io/linuxserver/qbittorrent:5.1.4"
  vaultwarden: "vaultwarden/server:1.34.3"
  plex: "lscr.io/linuxserver/plex:1.42.2"
  nextcloud: "nextcloud:32.0.3"
  postgres: "postgres:18.1"
  redis: "redis:8.4.0-alpine"
