---
# code: language=ansible

- name: Add folder for Docker files
  ansible.builtin.file:
    path: "{{ docker_path }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Add folders for Traefik files
  ansible.builtin.file:
    path: "{{ docker_path }}/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop:
    - traefik
    - traefik/ssl

- name: Check if Traefik compose exists
  ansible.builtin.stat:
    path: "{{ docker_path }}/traefik/docker-compose.yml"
  register: traefik_compose

- name: Check if the cert file exists
  ansible.builtin.stat:
    path: "{{ docker_path }}/traefik/ssl/cert.crt"
  register: fcrt

- name: Get cert expiration
  community.crypto.x509_certificate_info:
    path: "{{ docker_path }}/traefik/ssl/cert.crt"
  register: cert
  when: fcrt.stat.exists

- name: Decide if cert rotation is needed
  vars:
    cert_expire_epoch: "{{ (cert.not_after | to_datetime('%Y%m%d%H%M%SZ')).strftime('%s') | int }}"
    now_epoch: "{{ ansible_facts['date_time'].epoch | int }}"
  ansible.builtin.set_fact:
    cert_rotate: >-
      {{ (not fcrt.stat.exists) or
         ((cert_expire_epoch | default(0)) - now_epoch < 2592000) }}

- name: Rotate cert if expires in < 30 days
  ansible.builtin.file:
    path: "{{ docker_path }}/traefik/ssl/{{ item }}"
    state: absent
  loop:
    - cert.crt
    - cert.key
  when: cert_rotate

- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ docker_path }}/traefik/ssl/cert.key"
  when: cert_rotate

- name: Create CSR for self-signed certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ docker_path }}/traefik/ssl/cert.key"
    common_name: "*.{{ domain }}"
    subject_alt_name:
      - "DNS:*.{{ domain }}"
      - "DNS:{{ domain }}"
  register: csr
  when: cert_rotate

- name: Create self-signed certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ docker_path }}/traefik/ssl/cert.crt"
    csr_content: "{{ csr.csr }}"
    privatekey_path: "{{ docker_path }}/traefik/ssl/cert.key"
    provider: ownca
    ownca_path: "/home/{{ username }}/ca/ca.crt"
    ownca_privatekey_path: "/home/{{ username }}/ca/ca.key"
    ownca_not_after: +365d  # valid for one year
    ownca_not_before: "-1d"  # valid since yesterday
  when: cert_rotate

- name: Secure permissions for cert and key
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ docker_path }}/traefik/ssl/cert.key", mode: "0600" }
    - { path: "{{ docker_path }}/traefik/ssl/cert.crt", mode: "0644" }
  notify: Restart traefik
